version: '3.9'

services:
  backend:
    stdin_open: true
    image: mesabosque-backend:latest
    container_name: mesabosque-backend
    env_file:
      - .env
    environment:
      NODE_ENV: production
    restart: unless-stopped
    ports:
      - 3008:3000
    volumes:
      - ../../mesabosque-storage/:/app/storage
    networks:
      - net-mesabosque

  redis-mesabosque:
    image: redis:8.0.1-alpine3.21
    container_name: redis-mesabosque
    restart: unless-stopped
    sysctls:
      net.core.somaxconn: '511'
    expose:
      - '6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - ../../mesabosque-redis:/data
    networks:
      - net-mesabosque

networks:
  net-mesabosque:
    driver: bridge
