version: '3.9'

services:
  backend:
    stdin_open: true
    image: mesabosques-banckend:latest
    container_name: mesabosques-banckend
    env_file:
      - .env
    environment:
      NODE_ENV: production
    restart: unless-stopped
    ports:
      - 3009:3000
    volumes:
      - ../../mesabosques-storage/:/app/storage
    networks:
      - net-mesabosques

  redis-mesabosques:
    image: redis:8.0.1-alpine3.21
    container_name: redis-mesabosques
    restart: unless-stopped
    sysctls:
      net.core.somaxconn: '511'
    expose:
      - '6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - ../../mesabosques-redis:/data
    networks:
      - net-mesabosques

networks:
  net-mesabosques:
    driver: bridge
